### ISSUE TITLE
点开游戏模式时，最上面的 osu!mania 显示有问题

### ISSUE THREAD

**Issue by ak1ra-komj** [Sendevia/AincradMix#1]
点开游戏模式时，最上面的 osu!mania 显示有问题，当光标移动到 osu!mania 时会导致游戏奔溃，问题可重现。

**Comment by Sendevia** [comment]
@jiaxingzack 
显示问题的话可以麻烦提供个截图吗？
崩溃大概是因为图像的长度太长导致内存溢出了，，，下次的push我会解决的(ーωー)

**Comment by jiaxingzack** [comment]
正想重进游戏去截图，这次进去却一切正常。
之前是因为刚从默认皮肤切换过来导致的 bug 吗？现在不确定了。

**Comment by jiaxingzack** [comment]
这样，从默认皮肤切换到这个后显示有问题，光标移动到 osu!mania 上后游戏会崩溃；
另外还发现一个点，也是做了皮肤切换之后（没有重启尤其的情况下），游戏中 Esc 暂停时界面直接空白的；
![img](https://i.loli.net/2018/12/06/5c0944473840c.png)

**Comment by Sendevia** [comment]
@jiaxingzack 我明天尝试复现一下，看看是不是我能解决的吧(´･ᴗ･ ` )

**Comment by Sendevia** [comment]
@jiaxingzack 
用R_Sp[osu!]/Pack_[base]里的这四个

> [mode-osu-med@2x.png](https://raw.githubusercontent.com/Sendevia/R_Sp-osu-/master/R_Sp%5Bosu!%5D/Pack_%5Bbase%5D/mode-osu-med@2x.png)
> [mode-mania-med@2x.png](https://raw.githubusercontent.com/Sendevia/R_Sp-osu-/master/R_Sp%5Bosu!%5D/Pack_%5Bbase%5D/mode-mania-med@2x.png)
> [mode-taiko-med@2x.png](https://raw.githubusercontent.com/Sendevia/R_Sp-osu-/master/R_Sp%5Bosu!%5D/Pack_%5Bbase%5D/mode-taiko-med@2x.png)
> [mode-fruits-med@2x.png](https://raw.githubusercontent.com/Sendevia/R_Sp-osu-/master/R_Sp%5Bosu!%5D/Pack_%5Bbase%5D/mode-fruits-med@2x.png)

替换掉原来的，选模式时的崩溃和显示问题就没了 ~~（大概~~

**Comment by ak1ra-komj** [comment]
替换后好像确实没什么问题了；
特意切换成默认皮肤后重启游戏再切换到你这个皮肤，没有出现之前的问题。

**Comment by ak1ra-komj** [comment]
Hi,

抱歉重新开启这个 issue, 因为改了个用户名, 可以删除一下直接提及我的原用户名的回复吗? 现在 Google 搜索原用户名第一条就是这个 issue, GitHub 似乎不能删除整个 issue, 不过可以删除单条回复, 如果只是编辑的话会留下历史记录;

**Comment by sendevia** [comment]
已删除，但搜索引擎更新还得一段时间
